/* Real food & location data scraped from Google Places across the entire
   map around Sepang International Circuit.

   Generated by `scripts/scrape-sepang.mjs` (grid scrape, see that file for
   how it was gathered). This is the "latest data" backing the Paddock Mamak
   browse directory — every entry is a real, currently-listed place. */

import raw from "./sepang-places.json";

export type ScrapedCategory = "mamak" | "seafood" | "cafe" | "pitstop" | "south";

export type ScrapedPlace = {
  id: string;
  name: string;
  address: string;
  rating: number | null;
  userRatingCount: number | null;
  isOpen: boolean | null;
  priceLevel: string | null;
  types: string[];
  category: ScrapedCategory;
  summary: string;
  website: string;
  googleMapsUri: string;
  location: { lat: number; lng: number } | null;
  distanceKm?: number;
};

const CENTER = raw.center as { lat: number; lng: number };

function haversineKm(
  a: { lat: number; lng: number },
  b: { lat: number; lng: number },
) {
  const R = 6371;
  const dLat = ((b.lat - a.lat) * Math.PI) / 180;
  const dLng = ((b.lng - a.lng) * Math.PI) / 180;
  const lat1 = (a.lat * Math.PI) / 180;
  const lat2 = (b.lat * Math.PI) / 180;
  const h =
    Math.sin(dLat / 2) ** 2 +
    Math.sin(dLng / 2) ** 2 * Math.cos(lat1) * Math.cos(lat2);
  return 2 * R * Math.asin(Math.sqrt(h));
}

export const SEPANG_CENTER = CENTER;

export const SCRAPED_PLACES: ScrapedPlace[] = (
  raw.places as ScrapedPlace[]
).map((p) => ({
  ...p,
  distanceKm:
    p.location && p.location.lat && p.location.lng
      ? Math.round(haversineKm(CENTER, p.location) * 10) / 10
      : undefined,
}));

export const SCRAPED_SCRAPED_AT = raw.scrapedAt as string;
export const SCRAPED_COUNT = raw.count as number;

const dirFromCircuit = (placeId: string) =>
  `https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(
    "Sepang International Circuit",
  )}&destination_place_id=${placeId}`;

export const routeUrlFor = (p: ScrapedPlace) => dirFromCircuit(p.id);
